# Daniel Gisolfi

version: '2'
services:
  bot:
    build: .
    env_file: .env
    ports:
      - "5598:5598"
    environment: 
      BOT_ID: $BOT_ID
      GROUP_ID: $GROUP_ID
      API_TOKEN: $API_TOKEN